// Generated by CoffeeScript 1.9.3
(function() {
  var $;

  $ = {};

  $.remove = function(array, element) {
    var index, ref;
    if ((index = array.indexOf(element)) > -1) {
      [].splice.apply(array, [index, index - index + 1].concat(ref = [])), ref;
      return element;
    } else {
      return null;
    }
  };

  $.uniq = function(array, hash) {
    var element, k, key, l, len, len1, ref, results, uniques;
    if (hash == null) {
      hash = function(object) {
        return object.toString();
      };
    }
    uniques = {};
    for (k = 0, len = array.length; k < len; k++) {
      element = array[k];
      uniques[hash(element)] = element;
    }
    ref = Object.keys(uniques);
    results = [];
    for (l = 0, len1 = ref.length; l < len1; l++) {
      key = ref[l];
      results.push(uniques[key]);
    }
    return results;
  };

  $.shuffle = function(array) {
    var copy, i, j, k, ref, ref1;
    copy = array.slice(0);
    if (copy.length <= 1) {
      return copy;
    }
    for (i = k = ref = copy.length - 1; ref <= 1 ? k <= 1 : k >= 1; i = ref <= 1 ? ++k : --k) {
      j = Math.floor(Math.random() * (i + 1));
      ref1 = [copy[j], copy[i]], copy[i] = ref1[0], copy[j] = ref1[1];
    }
    return copy;
  };

  module.exports = $;

}).call(this);
