// Generated by CoffeeScript 1.9.3
(function() {
  var $, _module, basename, filename, i, include, len, readdir, ref;

  $ = {};

  $.w = function(string) {
    return string.trim().split(/\s+/);
  };

  $.to = function(to, from) {
    if (from instanceof to) {
      return from;
    } else {
      return new to(from);
    }
  };

  $.abort = function() {
    return process.exit(-1);
  };

  $.memoize = function(fn, hash) {
    var memo;
    if (hash == null) {
      hash = function(object) {
        return object.toString();
      };
    }
    memo = {};
    return function(thing) {
      var name;
      return memo[name = hash(thing)] != null ? memo[name] : memo[name] = fn(thing);
    };
  };


  /* timer */

  $.timer = function(wait, action) {
    var id;
    id = setTimeout(action, wait);
    return function() {
      return clearTimeout(id);
    };
  };

  basename = require("path").basename;

  readdir = require("./fs").readdir;

  include = require("./object").include;

  ref = readdir(__dirname);
  for (i = 0, len = ref.length; i < len; i++) {
    filename = ref[i];
    _module = basename(filename, ".coffee");
    if (_module !== "index") {
      include($, require("./" + _module));
    }
  }

  module.exports = $;

}).call(this);
