// Generated by CoffeeScript 1.9.3
(function() {
  var classToType, classes, i, len, name;

  classes = ["Boolean", "Number", "String", "Function", "Array", "Date", "RegExp"];

  classToType = new Object;

  for (i = 0, len = classes.length; i < len; i++) {
    name = classes[i];
    classToType["[object " + name + "]"] = name.toLowerCase();
  }

  module.exports = {
    type: function(object) {
      var myClass;
      if (object === void 0) {
        return "undefined";
      }
      if (object === null) {
        return "null";
      }
      myClass = Object.prototype.toString.call(object);
      if (myClass in classToType) {
        return classToType[myClass];
      } else {
        return "object";
      }
    }
  };

}).call(this);
